#######
# Compiled from data/learningmcscript/functions/load.mcscript
# to .//data/learningmcscript/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function learningmcscript:mcscript/load

