#######
# Compiled from data/learningmcscript/functions/main.mcscript
# to .//data/learningmcscript/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players add timer timer 1
execute if score timer timer matches 20.. as @a at @s if block ~ ~-1 ~ minecraft:grass_block run effect give @s minecraft:speed 1 1
execute if score timer timer matches 20.. run scoreboard players set timer timer 0
