#######
# Compiled from data/learningmcscript/functions/load.mcscript
# to .//data/learningmcscript/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######

# Extended from data/learningmcscript/functions/load.mcscript
# to data/learningmcscript/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add timer dummy
